// <auto-generated />
namespace NCSA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class changetoplayers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetoplayers));
        
        string IMigrationMetadata.Id
        {
            get { return "202007150347052_change to players"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
