// <auto-generated />
namespace NCSA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Addingitemstoteammodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingitemstoteammodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202102131455320_Adding items to team model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
