// <auto-generated />
namespace NCSA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Addfullnametouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addfullnametouser));
        
        string IMigrationMetadata.Id
        {
            get { return "202101080258569_Add full name to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
